service: aws-node-express-api-project
frameworkVersion: "3"

package:
  individually: true
custom:
  esbuild:
    bundle: true
    minify: false
    sourcemap: true
    exclude: ["aws-sdk"]
    target: "node14"
    define: { "require.resolve": undefined }
    platform: "node"
    concurrency: 10
    watch:
      pattern: ["src/**/*.ts"] # match only typescript files in src directory
      ignore: ["temp/**/*"]
  serverless-offline:
    noPrependStageInUrl: true

provider:
  name: aws
  runtime: nodejs14.x
  region: ap-northeast-1

functions:
  app:
    handler: src/handler.handler # 後で移動させる
    events:
      - http:
          method: ANY
          path: "/"
          cors: true
      - http:
          method: ANY
          path: "/{any+}"
          cors: true

plugins:
  - serverless-esbuild
  - serverless-offline
